### ISSUE TITLE
Question about NuGet package

### ISSUE THREAD

**Issue by lambdakris** [HydraCG/Heracles.net#2]
Greetings, I tried to consume Heracles.net through NuGet, and while I was able to find and install the package without issue (and I see it in my Package References/Dependencies) I am unable to reference any of the namespaces or types defined in the Heracles.net project. Is this a know/expected issue and/or is there a workaround of some sort?

Thank you very much

**Comment by alien-mcl** [comment]
Oh damn - package was utterly broken (nuget.exe V5 and newer is doing some weird stuff with custom crafted packages). I've uploaded a 0.5.1 version which should work correctly (I was able to import namespaces and types).

**Comment by lambdakris** [comment]
That fixed it! 

TY
